### ISSUE TITLE
We need a color scheme

### ISSUE THREAD

**Issue by piperswe** [SignumCollective/brand#1]
Any ideas?

**Comment by ztaylor54** [comment]
Not at the moment. I'll look into it

## Zachary Taylor

github.com/ztaylor54
ctftoolkit.com

**Comment by piperswe** [comment]
How about #34495E for primary and #80BA8E for secondary?

`#34495E`: ![#34495E](https://cloud.githubusercontent.com/assets/1830959/15332873/fb2007b6-1c2c-11e6-805c-96c94cd60c30.PNG)  
`#80BA8E`: ![80ba8e](https://cloud.githubusercontent.com/assets/1830959/15332947/419f6880-1c2d-11e6-9e35-e2de0a875ebe.PNG)

Vincent's working on a nice logo for us ;)

**Comment by piperswe** [comment]
@ztaylor54

**Comment by piperswe** [comment]
Alright, he says those aren't particularly bad, so @vincedesign I think those are the ones!
